### PR TITLE
Changes to build and packaging for ondemand 1.7

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
This PR will not work until OSC/ondemand#87 is merged and tagged into latest or ci repos.

**Comment by treydock** [comment]
This PR should be good to go.

**Comment by johrstrom** [comment]
This fails for me locally.  Is there any way to confirm it works, would I have to create a tag?

**Comment by treydock** [comment]
How did you build? It requires putting a tar ball in `packaging` directory with a version number and then building against that version. If the tar ball is not in `packaging` then the version is pulled from github and that won't use this pull request.  So if you pull in this PR do this:

```
git ls-files | gtar -c --transform 's,^,frame-renderer-0.3.0/,' -T - | gzip > packaging/v0.3.0.tar.gz
```

(Replace gtar with just tar if not using Mac)

Then can build package:

```
./build.sh -w /tmp/work -o /tmp/output -d el7 -V v0.3.0 -v ~/git/frame-renderer/packaging
```

I just built on my laptop successfully. If you don't want to do all these steps then this branch needs RC tag and that'll trigger Gitlab build using this PR.

**Comment by johrstrom** [comment]
OK yea, I was just making sure that it wasn't me that it would need some prep work to work.  Thanks!

**Pull request merged**
